### ISSUE TITLE
GHC 9.4 not supported due to transitive dependency constraint

### ISSUE THREAD

**Issue by hraftery** [sheaf/if-instance#2]
According to the [hackage listing](https://hackage.haskell.org/package/if-instance), the dependencies for `if-instance` 0.3.0.0 are:

> base (>=4.15.0 && <4.18), ghc (>=9.0 && <9.6), ghc-tcplugin-api (>=0.5.1.0 && <0.6)

which suggests that GHC 9.4.2 is supported. Alas, it seems that the only `ghc-tcplugin-api` satisfying (>=0.5.1.0 && <0.6) is 0.5.1.0, which has as [dependencies](https://hackage.haskell.org/package/ghc-tcplugin-api-0.5.1.0):

> base (>=4.14.0 && <4.18), ghc (>=8.10 && <9.4), transformers (>=0.5 && <0.6)

thus ruling out GHC 9.4 and above by association.

I have no idea if I'm doing this right, but at least for me I had to downgrade to GHC 9.2.5 to get `if-instance` to install using `cabal`, and I figured this is the reason.

**Comment by sheaf** [comment]
I've updated `ghc-tcplugin-api` to `0.9.0.0` for support of GHC 9.4 and 9.6, and updated this package to use this newer version of `ghc-tcplugin-api`. Let me know if that works for you and we can close this ticket. Thanks for your interest.

**Comment by hraftery** [comment]
Worked perfectly!

I did `cabal update` then `cabal install --lib if-instance` after confirming that cabal and ghc versions were 3.6.2.0 and 9.4.2 respectively. The new `if-instance-0.3.1.0` built and installed without issue, and I could see no issues compiling and running my little `-fplugin=IfSat.Plugin` test program.

Thanks for a great turn around.
