### ISSUE TITLE
GHC panic when trying to use the plugin

### ISSUE THREAD

**Issue by iand675** [sheaf/if-instance#3]
Hi, I'm trying to use this in a project to conditionally encode values via (JSON, Protobuf, direct binary encoding, etc.) where the first supported codec in a list is used: https://github.com/MercuryTechnologies/hs-temporal-sdk/commit/b95abc503a57df459e02d6abfb26740c4abe5d40

`if-instance` seems eminently suited for this purpose, but I'm unfortunately seeing a compiler crash when I use the plugin:

```
temporal-sdk> ghc: panic! (the 'impossible' happened)
temporal-sdk>   (GHC version 9.2.7:
temporal-sdk> 	refineFromInScope
temporal-sdk>   InScope {wild_00 wild_X1 client_agPK taskQueue_agPL wf_agPN
temporal-sdk>            $d||_ahi6 r_ahor a_ahos $dIP_ahyS makeClient needsClient rt spec
temporal-sdk>            uuidText withWorker $trModule $dIP_shFc $trModule_shFd
temporal-sdk>            $trModule_shFe $trModule_shFf $trModule_shFg $dMonadUnliftIO_shFj
temporal-sdk>            $dMonadLoggerIO_shFk}
temporal-sdk>   $dMessage_ahoq
temporal-sdk>   Call stack:
temporal-sdk>       CallStack (from HasCallStack):
temporal-sdk>         callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
temporal-sdk>         pprPanic, called at compiler/GHC/Core/Opt/Simplify/Env.hs:706:30 in ghc:GHC.Core.Opt.Simplify.Env
```

The above crash is triggered by building the test suite.

Here are trace dumps:

[IntegrationSpec.dump-cs-trace](https://github.com/sheaf/if-instance/files/12300010/IntegrationSpec.dump-cs-trace.txt)
[IntegrationSpec.dump-tc-trace](https://github.com/sheaf/if-instance/files/12300011/IntegrationSpec.dump-tc-trace.txt)

I'm unfortunately not super-well versed in plugin implementation, but I'm hoping you could help resolve the issue.

**Comment by sheaf** [comment]
Thanks for the bug report. I've pushed a commit which fixes a bug with the library, and I'm hoping it might also address your issue. Unfortunately, I don't have the time to check your reproducer at the moment. If the plugin still panics for you, could you perhaps try to distill the reproducer a bit more?

**Comment by iand675** [comment]
I can confirm that fixes it! Thanks so much for the quick response!
